try a before script - will it fold and hide all the code? and having it at the end looks weird but it doesn't like to have it before any "real" script keys

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -50,40 +50,6 @@ jobs:
   #############################################################################
     # Workflow: scriptValidation
     - script:
-      - |
-        # Convenience scripts for Travis fold. Based on these scripts:
-        # * https://github.com/spotify/ios-ci/blob/master/bin/travis_fold
-        # * https://www.koszek.com/blog/2016/07/25/dealing-with-large-jobs-on-travis/
-        tmpFoldName=/tmp/.travis_fold_name
-        tmpFoldHeading=/tmp/.travis_fold_heading
-
-        FOLD_START() {
-          local action=start
-          local name=$1
-          # Add a lot of space (tabs) to heading to extend the background color
-          local heading="  $2  \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"
-
-          # Gray bg, Yellow fg, and use \r to overwrite the "travis_fold:action:name" as it's just annoying
-          echo -en "travis_fold:${action}:${name}\r\e[40;33m${heading}\n"
-
-          # Save the current scope, so we can call FOLD_END without passing them again
-          /bin/echo -n "$name" > "$tmpFoldName"
-          /bin/echo -n "$heading" > "$tmpFoldHeading"
-        }
-
-        FOLD_END() {
-          local exitCode=$?
-          local action=end
-          local name=$(cat "${tmpFoldName}")
-          local heading=$(cat "${tmpFoldHeading}")
-
-          # Black bg, Grey fg, and use \r to overwrite the "travis_fold:action:name" as it's just annoying
-          echo -en "travis_fold:${action}:${name}\r\e[100;30m${heading}\n"
-
-          # Return the exit code otherwise the step won't fail if there was a failure
-          return "$exitCode"
-        }
-
       # Start Docker
       - FOLD_START docker_start "Start Docker"
       - |
@@ -135,5 +101,40 @@ jobs:
       - FOLD_START az_teardown "Teardown Azure resources"
       - docker exec "$CONTAINER_NAME" /bin/bash -c "cd retro-cloud-setup && bash teardown.sh '$CONTAINER_NAME'" ; FOLD_END
       # when: always
+
+      before_script:
+      - |
+        # Convenience scripts for Travis fold. Based on these scripts:
+        # * https://github.com/spotify/ios-ci/blob/master/bin/travis_fold
+        # * https://www.koszek.com/blog/2016/07/25/dealing-with-large-jobs-on-travis/
+        tmpFoldName=/tmp/.travis_fold_name
+        tmpFoldHeading=/tmp/.travis_fold_heading
+
+        FOLD_START() {
+          local action=start
+          local name=$1
+          # Add a lot of space (tabs) to heading to extend the background color
+          local heading="  $2  \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"
+
+          # Gray bg, Yellow fg, and use \r to overwrite the "travis_fold:action:name" as it's just annoying
+          echo -en "travis_fold:${action}:${name}\r\e[40;33m${heading}\n"
+
+          # Save the current scope, so we can call FOLD_END without passing them again
+          /bin/echo -n "$name" > "$tmpFoldName"
+          /bin/echo -n "$heading" > "$tmpFoldHeading"
+        }
+
+        FOLD_END() {
+          local exitCode=$?
+          local action=end
+          local name=$(cat "${tmpFoldName}")
+          local heading=$(cat "${tmpFoldHeading}")
+
+          # Black bg, Grey fg, and use \r to overwrite the "travis_fold:action:name" as it's just annoying
+          echo -en "travis_fold:${action}:${name}\r\e[100;30m${heading}\n"
+
+          # Return the exit code otherwise the step won't fail if there was a failure
+          return "$exitCode"
+        }
 
       name: "scriptValidation"
